
export { CartIcon } from './carticon';
export { EmailIcon } from './emailicon';
export { InstagramIcon } from './instagramicon';
export { KokaashIcon } from './kokasshicon';
export { PhoneIcon } from './phoneicon';
export { SearchIcon } from './searchicon';
export { SignArrowIcon } from './signarrowicon';
export { SignIcon } from './signicon';
export { WishlistIcon } from './wishlisticon';
export { VisaIcon } from './visaicon';
export { MastercardIcon } from './mastercardicon';
export { ArrowIcon } from './arrowicon';
export { FooterImg } from './footerimg';
export { PasswordIcon } from './passwordicon';
export { GmailIcon } from './gmailicon';
export { FacebookIcon } from './facebookicon';
export { AppleIcon } from './appleicon';
export { WishlistArrowIcon } from './wishlistarrowicon';
export { ProductWishListIcon } from './productwishlisticon';
export { ProductCartIcon } from './productcarticon';
export { MyOrdersArrowIcon } from './myordersarrowicon';
export { AccountInfoImg } from './accinfoimg';
export { ExitIcon } from './exiticon';
export { DropDownArrowIcon } from './dropdownarrowicon';
export { PaymentMethodIcon } from './paymentmethodicon';
export { ApplePayIcon } from './applepayicon';
export { BoxIcon, CarIcon, SecureIcon, QtyAddIcon, QtySubIcon } from './producticons';
export { FilterArrowDownIcon, FilterArrowUpIcon, FilterCheckBoxIcon, FilterDeleteIcon } from './filtericons';
export { AddIcon, DeleteIcon, SubIcon } from './cartmobileicons';
export { BoyAndGirlMobileIcon, RightMobileIcon } from './SignupSuccessMobile';
export { OrderRightMobileIcon } from './OrderSuccessMobile';
