export const cartItems = [
  {
    image: "images/cart-image1.png",
    number: "432-123",
    order: "Hodiee Girl",
    size: "0-3 months",
    quantity: 1,
    color: "#66457E",
    price: 200,
  },
  {
    image: "images/cart-image2.png",
    number: "532-533",
    order: "Pink Pants baby",
    size: "3-6 months",
    quantity: 2,
    color: "#F174A7",
    price: 100,
  },
  {
    image: "images/cart-image3.png",
    number: "412-212",
    order: "Blue T-shirt",
    size: "3 years",
    quantity: 5,
    color: "#FFD89F",
    price: 500,
  },
  {
    image: "images/cart-image4.png",
    number: "909-255",
    order: "Violet T-shirt",
    size: "1 year",
    quantity: 3,
    color: "#FFD89F",
    price: 300,
  },
  {
    image: "images/cart-image5.png",
    number: "190-189",
    order: "Baby blue skirt",
    size: "6-9 months",
    quantity: 4,
    color: "#FFD89F",
    price: 200,
  },
  {
    image: "images/cart-image6.png",
    number: "191-887",
    order: "Pinky Short",
    size: "4-5 months",
    quantity: 1,
    color: "#FFD89F",
    price: 100,
  },
];
