import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Menubar from "../components/Menubar/Menubar";
import Head from "../../node_modules/next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kokaash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </head>
      <body className="mx-auto flex flex-col font-GothamLight w-full min-w-screen-md">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
